#!/bin/bash

ccktools_newproject(){
clear
  echo "Buscando archivos bin en la carpeta watchfaces (solo trabajaré con el primero que encuentre)"
  cd watchfaces
  nombredelarchivo=(*.bin)
  echo ${nombredelarchivo[0]}
  cd ..
  if [[ ! -f watchfaces/${nombredelarchivo} ]]; then
  	echo "no existe"
  	exit
  	break
  fi
  fullname=$(basename "${nombredelarchivo}")
  extension="${fullname##*.}"
  filename="${fullname%.*}"
  if [[ ${extension} == 'bin' ]]; then
    echo "----------------"
    echo "--- BIN MODE ---"
    echo "----------------"
    workingtype='bin'
  elif [[ ${extension} == 'res' ]]; then
    echo "----------------"
    echo "--- RES MODE ---"
    echo "----------------"
    echo "--- NO SOPORTADO"
    workingtype='res'
    exit
    break
  fi
  echo "-----"
  echo "----- ${fullname} "
  filedir=watchfaces/build_${filename}/
  echo "----- ${filedir} "
  if [[ ! -d ${filedir} ]]; then
    echo "----- Creando ${filedir}"
    mkdir -p ${filedir}/
    mv watchfaces/${fullname} ${filedir}/
    cp dependencies/dial2img.py ${filedir}/
    echo "#!/bin/bash
./dial2img.py -u -i ${fullname}" >> ${filedir}/descompilar
    echo "#!/bin/bash
current_time=\$(\date \"+%Y.%m.%d-%H.%M.%S\")
if [[ ! -d old ]]; then
	mkdir old
fi
mv ${filename}_*.bin old
./dial2img.py -i ${fullname} -p
echo \"renombrado a ${filename}_\${current_time}.${extension}\"
mv ${fullname}.new ${filename}_\${current_time}.${extension}
adb push ${filename}_\${current_time}.bin /sdcard/Download/
" >> ${filedir}/compilar
    chmod +x ${filedir}/dial2img.py
    chmod +x ${filedir}/descompilar
    chmod +x ${filedir}/compilar
  else
    echo "----- Ya existe /${filedir}, prueba otro nombre, o renombra el existente"
  fi
  echo "-----"
  echo "----------------"
  echo ""
  echo ""
  echo ""
  cd ${filedir}
  open .
  open -a Terminal "`pwd`"
  ./descompilar
}

ccktools_auto(){
  echo "----- Modo automático"
  ccktools_newproject
}

ccktools_auto


